# Generated by Django 4.0.6 on 2022-07-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ichkiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savat',
            name='miqdor',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
