# Generated by Django 4.0.6 on 2022-07-31 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alistyleapp', '0007_alter_comment_mahsulot'),
        ('Ichkiapp', '0002_alter_savat_miqdor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanlangan',
            name='mahsulot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahsulot_tanlangan', to='Alistyleapp.mahsulot'),
        ),
    ]
