# Generated by Django 4.0.6 on 2022-08-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ichkiapp', '0004_alter_buyurtma_savat_alter_buyurtma_yet_narx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyurtma',
            name='yet_narx',
            field=models.PositiveSmallIntegerField(default=5000),
        ),
    ]
