# Generated by Django 4.0.6 on 2022-07-30 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alistyleapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='chegirma',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ichki',
            name='bolim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bolim_ichkilari', to='Alistyleapp.bolim'),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='ichki',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ichki_mahsulotlar', to='Alistyleapp.ichki'),
        ),
        migrations.AlterField(
            model_name='media',
            name='mahsulot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mahsulot_medialar', to='Alistyleapp.mahsulot'),
        ),
    ]
