# Generated by Django 4.0.6 on 2022-07-31 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alistyleapp', '0002_mahsulot_chegirma_alter_ichki_bolim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='olchov',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
