# Generated by Django 4.0.6 on 2022-07-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alistyleapp', '0003_mahsulot_olchov'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='min_buyurtma',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
