# Generated by Django 4.0.6 on 2022-07-31 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0002_alter_account_user'),
        ('Alistyleapp', '0004_mahsulot_min_buyurtma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izoh', models.CharField(max_length=300)),
                ('baho', models.PositiveSmallIntegerField(default=4)),
                ('sana', models.DateField(auto_now_add=True)),
                ('mijoz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Userapp.account')),
            ],
        ),
    ]
