# Generated by Django 4.0.6 on 2022-07-31 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alistyleapp', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='mahsulot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Alistyleapp.mahsulot'),
        ),
    ]
